### ISSUE TITLE
Erro python cv2

### ISSUE THREAD

**Issue by habubo** [alyleite/bbbot#10]
Tive o seguinte erro:
Logged in.
Download captcha from URL: moto
Traceback (most recent call last):
  File "./src/compare_images.py", line 57, in <module>
    diff = compare_image(existent_image_path, captcha_part)
  File "./src/compare_images.py", line 33, in compare_image
    diff = calculate_diff(img1, img2)
  File "./src/compare_images.py", line 14, in calculate_diff
    matcher = cv2.xfeatures2d.SIFT_create(nfeatures=100)
AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'

**Comment by matheusmhpc** [comment]
entra na pasta e roda "pip3 install -r requirements.txt" e "pip install -r requirements.txt"
